//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermalis.VGMusicStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kermalis.VGMusicStudio.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} key ähnelt.
        /// </summary>
        internal static string ConfigKeySubkey {
            get {
                return ResourceManager.GetString("ConfigKeySubkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to stop playing the current playlist? ähnelt.
        /// </summary>
        internal static string EndPlaylistBody {
            get {
                return ResourceManager.GetString("EndPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; must be True or False. ähnelt.
        /// </summary>
        internal static string ErrorBoolParse {
            get {
                return ResourceManager.GetString("ErrorBoolParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color {0} has an invalid key. ähnelt.
        /// </summary>
        internal static string ErrorConfigColorInvalidKey {
            get {
                return ResourceManager.GetString("ErrorConfigColorInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color {0} is not defined. ähnelt.
        /// </summary>
        internal static string ErrorConfigColorMissing {
            get {
                return ResourceManager.GetString("ErrorConfigColorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color {0} is defined more than once between decimal and hexadecimal. ähnelt.
        /// </summary>
        internal static string ErrorConfigColorRepeated {
            get {
                return ResourceManager.GetString("ErrorConfigColorRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is invalid. ähnelt.
        /// </summary>
        internal static string ErrorConfigKeyInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is missing. ähnelt.
        /// </summary>
        internal static string ErrorConfigKeyMissing {
            get {
                return ResourceManager.GetString("ErrorConfigKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; must have at least one entry. ähnelt.
        /// </summary>
        internal static string ErrorConfigKeyNoEntries {
            get {
                return ResourceManager.GetString("ErrorConfigKeyNoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown header version: 0x{0:X} ähnelt.
        /// </summary>
        internal static string ErrorDSEInvalidHeaderVersion {
            get {
                return ResourceManager.GetString("ErrorDSEInvalidHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid key in track {0} at 0x{1:X}: {2} ähnelt.
        /// </summary>
        internal static string ErrorDSEInvalidKey {
            get {
                return ResourceManager.GetString("ErrorDSEInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid command in track {0} at 0x{1:X}: 0x{2:X} ähnelt.
        /// </summary>
        internal static string ErrorDSEMLSSMP2KSDATInvalidCommand {
            get {
                return ResourceManager.GetString("ErrorDSEMLSSMP2KSDATInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no &quot;bgm(NNNN).smd&quot; files. ähnelt.
        /// </summary>
        internal static string ErrorDSENoSequences {
            get {
                return ResourceManager.GetString("ErrorDSENoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading Global Config ähnelt.
        /// </summary>
        internal static string ErrorGlobalConfig {
            get {
                return ResourceManager.GetString("ErrorGlobalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading Song {0} ähnelt.
        /// </summary>
        internal static string ErrorLoadSong {
            get {
                return ResourceManager.GetString("ErrorLoadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot copy invalid game code &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string ErrorMLSSMP2KCopyInvalidGameCode {
            get {
                return ResourceManager.GetString("ErrorMLSSMP2KCopyInvalidGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game code &quot;{0}&quot; is missing. ähnelt.
        /// </summary>
        internal static string ErrorMLSSMP2KMissingGameCode {
            get {
                return ResourceManager.GetString("ErrorMLSSMP2KMissingGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error parsing game code &quot;{0}&quot; in &quot;{1}&quot;{2} ähnelt.
        /// </summary>
        internal static string ErrorMLSSMP2KParseGameCode {
            get {
                return ResourceManager.GetString("ErrorMLSSMP2KParseGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playlist &quot;{0}&quot; has song {1} defined more than once between decimal and hexadecimal. ähnelt.
        /// </summary>
        internal static string ErrorMLSSMP2KSongRepeated {
            get {
                return ResourceManager.GetString("ErrorMLSSMP2KSongRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; count must be the same as &quot;{1}&quot; count. ähnelt.
        /// </summary>
        internal static string ErrorMLSSMP2KSongTableCounts {
            get {
                return ResourceManager.GetString("ErrorMLSSMP2KSongTableCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid running status command in track {0} at 0x{1:X}: 0x{2:X} ähnelt.
        /// </summary>
        internal static string ErrorMP2KInvalidRunningStatusCommand {
            get {
                return ResourceManager.GetString("ErrorMP2KInvalidRunningStatusCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many nested call events in track {0} ähnelt.
        /// </summary>
        internal static string ErrorMP2KSDATNestedCalls {
            get {
                return ResourceManager.GetString("ErrorMP2KSDATNestedCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading DSE Folder ähnelt.
        /// </summary>
        internal static string ErrorOpenDSE {
            get {
                return ResourceManager.GetString("ErrorOpenDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading GBA ROM (MLSS) ähnelt.
        /// </summary>
        internal static string ErrorOpenMLSS {
            get {
                return ResourceManager.GetString("ErrorOpenMLSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading GBA ROM (MP2K) ähnelt.
        /// </summary>
        internal static string ErrorOpenMP2K {
            get {
                return ResourceManager.GetString("ErrorOpenMP2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading SDAT File ähnelt.
        /// </summary>
        internal static string ErrorOpenSDAT {
            get {
                return ResourceManager.GetString("ErrorOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error parsing &quot;{0}&quot;{1} ähnelt.
        /// </summary>
        internal static string ErrorParseConfig {
            get {
                return ResourceManager.GetString("ErrorParseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Exporting MIDI ähnelt.
        /// </summary>
        internal static string ErrorSaveMIDI {
            get {
                return ResourceManager.GetString("ErrorSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Exporting WAV ähnelt.
        /// </summary>
        internal static string ErrorSaveWAV {
            get {
                return ResourceManager.GetString("ErrorSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This SDAT archive has no sequences. ähnelt.
        /// </summary>
        internal static string ErrorSDATNoSequences {
            get {
                return ResourceManager.GetString("ErrorSDATNoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is not an integer value. ähnelt.
        /// </summary>
        internal static string ErrorValueParse {
            get {
                return ResourceManager.GetString("ErrorValueParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; must be between {1} and {2}. ähnelt.
        /// </summary>
        internal static string ErrorValueParseRanged {
            get {
                return ResourceManager.GetString("ErrorValueParseRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GBA Files ähnelt.
        /// </summary>
        internal static string FilterOpenGBA {
            get {
                return ResourceManager.GetString("FilterOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SDAT Files ähnelt.
        /// </summary>
        internal static string FilterOpenSDAT {
            get {
                return ResourceManager.GetString("FilterOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIDI Files ähnelt.
        /// </summary>
        internal static string FilterSaveMIDI {
            get {
                return ResourceManager.GetString("FilterSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WAV Files ähnelt.
        /// </summary>
        internal static string FilterSaveWAV {
            get {
                return ResourceManager.GetString("FilterSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Current Playlist ähnelt.
        /// </summary>
        internal static string MenuEndPlaylist {
            get {
                return ResourceManager.GetString("MenuEndPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open DSE Folder ähnelt.
        /// </summary>
        internal static string MenuOpenDSE {
            get {
                return ResourceManager.GetString("MenuOpenDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open GBA ROM (MLSS) ähnelt.
        /// </summary>
        internal static string MenuOpenMLSS {
            get {
                return ResourceManager.GetString("MenuOpenMLSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open GBA ROM (MP2K) ähnelt.
        /// </summary>
        internal static string MenuOpenMP2K {
            get {
                return ResourceManager.GetString("MenuOpenMP2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open SDAT File ähnelt.
        /// </summary>
        internal static string MenuOpenSDAT {
            get {
                return ResourceManager.GetString("MenuOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playlist ähnelt.
        /// </summary>
        internal static string MenuPlaylist {
            get {
                return ResourceManager.GetString("MenuPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export All Songs as WAV ähnelt.
        /// </summary>
        internal static string MenuSaveAllWAV {
            get {
                return ResourceManager.GetString("MenuSaveAllWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Song as MIDI ähnelt.
        /// </summary>
        internal static string MenuSaveMIDI {
            get {
                return ResourceManager.GetString("MenuSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Song as WAV ähnelt.
        /// </summary>
        internal static string MenuSaveWAV {
            get {
                return ResourceManager.GetString("MenuSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C;C#;D;D#;E;F;F#;G;G#;A;A#;B ähnelt.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Song ähnelt.
        /// </summary>
        internal static string PlayerNextSong {
            get {
                return ResourceManager.GetString("PlayerNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        internal static string PlayerNotes {
            get {
                return ResourceManager.GetString("PlayerNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string PlayerPause {
            get {
                return ResourceManager.GetString("PlayerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string PlayerPlay {
            get {
                return ResourceManager.GetString("PlayerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        internal static string PlayerPosition {
            get {
                return ResourceManager.GetString("PlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Song ähnelt.
        /// </summary>
        internal static string PlayerPreviousSong {
            get {
                return ResourceManager.GetString("PlayerPreviousSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rest ähnelt.
        /// </summary>
        internal static string PlayerRest {
            get {
                return ResourceManager.GetString("PlayerRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string PlayerStop {
            get {
                return ResourceManager.GetString("PlayerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tempo ähnelt.
        /// </summary>
        internal static string PlayerTempo {
            get {
                return ResourceManager.GetString("PlayerTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        internal static string PlayerType {
            get {
                return ResourceManager.GetString("PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unpause ähnelt.
        /// </summary>
        internal static string PlayerUnpause {
            get {
                return ResourceManager.GetString("PlayerUnpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music ähnelt.
        /// </summary>
        internal static string PlaylistMusic {
            get {
                return ResourceManager.GetString("PlaylistMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to play the following playlist?{0} ähnelt.
        /// </summary>
        internal static string PlayPlaylistBody {
            get {
                return ResourceManager.GetString("PlayPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All WAVs have been exported! ähnelt.
        /// </summary>
        internal static string SuccessSaveAllWAV {
            get {
                return ResourceManager.GetString("SuccessSaveAllWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIDI saved to {0}. ähnelt.
        /// </summary>
        internal static string SuccessSaveMIDI {
            get {
                return ResourceManager.GetString("SuccessSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WAV saved to {0}. ähnelt.
        /// </summary>
        internal static string SuccessSaveWAV {
            get {
                return ResourceManager.GetString("SuccessSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arguments ähnelt.
        /// </summary>
        internal static string TrackViewerArguments {
            get {
                return ResourceManager.GetString("TrackViewerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event ähnelt.
        /// </summary>
        internal static string TrackViewerEvent {
            get {
                return ResourceManager.GetString("TrackViewerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        internal static string TrackViewerOffset {
            get {
                return ResourceManager.GetString("TrackViewerOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ticks ähnelt.
        /// </summary>
        internal static string TrackViewerTicks {
            get {
                return ResourceManager.GetString("TrackViewerTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track Viewer ähnelt.
        /// </summary>
        internal static string TrackViewerTitle {
            get {
                return ResourceManager.GetString("TrackViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track {0} ähnelt.
        /// </summary>
        internal static string TrackViewerTrackX {
            get {
                return ResourceManager.GetString("TrackViewerTrackX", resourceCulture);
            }
        }
    }
}
